name: CI for Twitch Chat Analysis Project

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install ruff
      
      - name: Lint with Ruff
        run: ruff check .
      
      - name: Check Formatting
        run: ruff format --check .